import React from "react";

export type CultureThemeId = string;

export interface CultureThemeConfig {
  id: CultureThemeId;
  name: string;
  nameHindi: string;
  bgGradient: string; // Header background Tailwind class
  heroGradient: string; // Hero section background Tailwind class
  bannerText: string;
  primaryColor: string; // E.g. "rgb(204, 0, 0)" / hex
  buttonBg: string; // E.g. "bg-amber-400 text-slate-950"
  accentBorder: string; // E.g. "border-amber-400"
  localGreeting: string;
  englishGreeting: string;
  culturalDescription: string;
  heritageMotif: string; // Describe decorative background item
  tagBg: string;
  hoverTextColor: string;
  icon: string; // Emoji representing state
}

export const CULTURE_THEMES: Record<string, CultureThemeConfig> = {
  national: {
    id: "national",
    name: "National Portal",
    nameHindi: "राष्ट्रीय पोर्टल • सत्यमेव जयते",
    bgGradient: "bg-[#cc0000]",
    heroGradient: "from-[#0c1445] via-[#040824] to-[#04082a]",
    bannerText: "🇮🇳 भारत का #1 विश्वसनीय सरकारी नौकरी पोर्टल",
    primaryColor: "#cc0000",
    buttonBg: "bg-amber-400 text-slate-950 hover:bg-amber-300",
    accentBorder: "border-amber-400",
    localGreeting: "सत्यमेव जयते • सरकारी नौकरी द्वार",
    englishGreeting: "Official Central & State Sarkari Gateway",
    culturalDescription: "Unified National Central Careers Portal - Bridging authentic job notifications, results, and admit cards for all Indian youth across 37 States & UTs.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-amber-400",
    hoverTextColor: "hover:text-amber-300",
    icon: "🇮🇳"
  },
  UP: {
    id: "UP",
    name: "Uttar Pradesh",
    nameHindi: "उत्तर प्रदेश राज्य द्वार • नमस्कार",
    bgGradient: "bg-orange-700",
    heroGradient: "from-[#4c1d11] via-[#1c0702] to-[#0f0300]",
    bannerText: "🚩 Sangam City & Ram Janmabhoomi Careers Gateway",
    primaryColor: "#c2410c",
    buttonBg: "bg-amber-500 text-neutral-900 hover:bg-amber-400",
    accentBorder: "border-amber-500",
    localGreeting: "उत्तर प्रदेश सरकार भर्तियां प्रभाग",
    englishGreeting: "Namaskar! Welcome to the Holy Land of Ganga & Sangams",
    culturalDescription: "Explore careers in India's most populous heritage state - from the ancient steps of Varanasi ghāts and divine Ayodhya temples to the royal Lucknow Taj.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-orange-600",
    hoverTextColor: "hover:text-amber-300",
    icon: "🚩"
  },
  BR: {
    id: "BR",
    name: "Bihar",
    nameHindi: "बिहार राज्य • प्रणाम",
    bgGradient: "bg-[#b45309]",
    heroGradient: "from-[#451a03] via-[#1a0700] to-[#0b0300]",
    bannerText: "🎓 Land of Patliputra, Nalanda & Bodhi Wisdom",
    primaryColor: "#b45309",
    buttonBg: "bg-yellow-400 text-slate-950 hover:bg-yellow-300",
    accentBorder: "border-yellow-400",
    localGreeting: "बिहार लोक सेवा आयोग नौकरी मंच",
    englishGreeting: "Chhath Sandhya Pranam! Welcome to the Soil of Nalanda",
    culturalDescription: "The absolute cradle of ancient Indian administration, Maurya dynasty, sacred Mahabodhi tree, Madhubani canvas folk arts, and historic IAS hubs.",
    heritageMotif: "alpana",
    tagBg: "bg-amber-600",
    hoverTextColor: "hover:text-yellow-305",
    icon: "🎓"
  },
  RJ: {
    id: "RJ",
    name: "Rajasthan",
    nameHindi: "राजस्थान राज्य • खम्मा घणी",
    bgGradient: "bg-[#e11d48]",
    heroGradient: "from-[#4c0519] via-[#1f0007] to-[#140003]",
    bannerText: "🏰 Royal Forts & Heritage Golden Desert Sands",
    primaryColor: "#e11d48",
    buttonBg: "bg-amber-400 text-neutral-900 hover:bg-amber-300",
    accentBorder: "border-amber-400",
    localGreeting: "पधारो म्हारे देस • राजस्थान नौकरियाँ",
    englishGreeting: "Khamma Ghani! Greeting from the Land of Maharajas",
    culturalDescription: "Savor the majestic aesthetics of Jaipur Pink City, the massive golden Mehrangarh forts, Lake Pichola palaces, and rich Rajasthani Ghoomar folk tunes.",
    heritageMotif: "kathakali",
    tagBg: "bg-rose-600",
    hoverTextColor: "hover:text-amber-300",
    icon: "🏰"
  },
  MP: {
    id: "MP",
    name: "Madhya Pradesh",
    nameHindi: "मध्य प्रदेश • जय हिन्द",
    bgGradient: "bg-[#15803d]",
    heroGradient: "from-[#052e16] via-[#021405] to-[#010802]",
    bannerText: "🐅 Heart of India & Pristine Tiger Reserves",
    primaryColor: "#15803d",
    buttonBg: "bg-amber-400 text-slate-950 hover:bg-amber-300",
    accentBorder: "border-amber-400",
    localGreeting: "मध्य प्रदेश रोजगार सूचना केंद्र",
    englishGreeting: "Namaste! Welcome to the Heart of Incredible India",
    culturalDescription: "Home to divine Sanchi Stupas, spectacular temples of Khajuraho, dense green tiger reserves of Kanha, and royal Gwalior fortresses.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-green-605",
    hoverTextColor: "hover:text-amber-300",
    icon: "🐅"
  },
  MH: {
    id: "MH",
    name: "Maharashtra",
    nameHindi: "महाराष्ट्र राज्य • जय महाराष्ट्र",
    bgGradient: "bg-[#ea580c]",
    heroGradient: "from-[#431407] via-[#1c0200] to-[#0f0100]",
    bannerText: "🦁 Chhatrapati Shivaji Maharaj Legacy Offices",
    primaryColor: "#ea580c",
    buttonBg: "bg-yellow-400 text-slate-900 hover:bg-yellow-300",
    accentBorder: "border-yellow-400",
    localGreeting: "महाराष्ट्र शासकीय सेवा नोकरी माहिती",
    englishGreeting: "Jai Maharashtra! Saluting Chhatrapati Shivaji’s Land",
    culturalDescription: "Bridging Mumbai's financial heart with ancient Ajanta & Ellora caves, historical forts of Sahyadri, and the beautiful festive energy of Ganesh Chaturthi.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-orange-600",
    hoverTextColor: "hover:text-yellow-300",
    icon: "🦁"
  },
  DL: {
    id: "DL",
    name: "Delhi",
    nameHindi: "दिल्ली संस्कृति • नमस्ते",
    bgGradient: "bg-[#1e1b4b]",
    heroGradient: "from-[#111827] via-[#030712] to-[#090514]",
    bannerText: "🏛️ Dilwalon Ki Dilli • National Capital Region Careers",
    primaryColor: "#1e1b4b",
    buttonBg: "bg-orange-500 text-white hover:bg-orange-400",
    accentBorder: "border-orange-400",
    localGreeting: "दिल्ली सरकारी नौकरी सूचना द्वार",
    englishGreeting: "Namaste Delhi! (दिल्ली में आपका स्वागत है!)",
    culturalDescription: "Welcome to the Historical Capital - Blending majesty, central gardens, ancient sandstone heritage of the Red Fort & India Gate, and the dynamic energy of India's cultural heartbeat.",
    heritageMotif: "india-gate",
    tagBg: "bg-[#1e1b4b]",
    hoverTextColor: "hover:text-orange-400",
    icon: "🏛️"
  },
  WB: {
    id: "WB",
    name: "West Bengal",
    nameHindi: "পশ্চিমবঙ্গ সংস্কৃতির থিম • শুভ স্বাগত",
    bgGradient: "bg-[#990011]",
    heroGradient: "from-[#4a0007] via-[#200000] to-[#150002]",
    bannerText: "🌾 সোনার বাংলা • West Bengal State Culture & Jobs Dashboard",
    primaryColor: "#990011",
    buttonBg: "bg-[#ffd700] text-slate-950 hover:bg-amber-300",
    accentBorder: "border-[#ffd700]",
    localGreeting: "পশ্চিমবঙ্গ সরকারি চাকরি প্রার্থী পোর্টাল",
    englishGreeting: "Subho Swagatham! (শুভ স্বাগত!)",
    culturalDescription: "Welcome to Sonar Bangla - Honoring the soil of Kabiguru Rabindranath Tagore, Netaji Subhas Chandra Bose, the majestic Howrah Bridge, rich terracotta architectures of Bishnupur, and the spirit of Durga Puja.",
    heritageMotif: "alpana",
    tagBg: "bg-red-600",
    hoverTextColor: "hover:text-yellow-300",
    icon: "🌾"
  },
  TN: {
    id: "TN",
    name: "Tamil Nadu",
    nameHindi: "தமிழ்நாடு அரசு • வணக்கம்",
    bgGradient: "bg-[#800020]",
    heroGradient: "from-[#33000b] via-[#100002] to-[#040000]",
    bannerText: "🛕 Thanjavur Gopuram Heritage & Tamil Careers",
    primaryColor: "#800020",
    buttonBg: "bg-yellow-450 text-slate-900 hover:bg-yellow-350",
    accentBorder: "border-amber-400",
    localGreeting: "வேலைவாய்ப்பு மற்றும் பயிற்சித் துறை",
    englishGreeting: "Vanakkam! Honouring Sacred Sangam Tamil Culture & Chola Gopurams",
    culturalDescription: "Steeped in ancient Dravidian heritage, Bharatanatyam, the massive stone architecture of Madurai Meenakshi, and delicious filter-coffee mornings.",
    heritageMotif: "kathakali",
    tagBg: "bg-rose-950",
    hoverTextColor: "hover:text-yellow-300",
    icon: "🛕"
  },
  KA: {
    id: "KA",
    name: "Karnataka",
    nameHindi: "ಕರ್ನಾಟಕ ತಂತ್ರಜ್ಞಾನ • ನಮಸ್ಕಾರ",
    bgGradient: "bg-[#b45309]",
    heroGradient: "from-[#3f1301] via-[#140400] to-[#080205]",
    bannerText: "🏛️ Hampi Ruins Heritage & Silicon Valley of India",
    primaryColor: "#b45309",
    buttonBg: "bg-amber-400 text-slate-950 hover:bg-amber-300",
    accentBorder: "border-yellow-400",
    localGreeting: "ಕರ್ನಾಟಕ ಉದ್ಯೋಗ ಸಹಾಯವಾಣಿ",
    englishGreeting: "Namaskara! Cradle of Sandalwood Craft & Tech Hubs",
    culturalDescription: "Embodying the glorious Vijayanagara stone temples of Hampi, high-tech Bangalore tech parks, regal Mysore Dussehra, and lovely Yakshagana dance theatres.",
    heritageMotif: "alpana",
    tagBg: "bg-amber-700",
    hoverTextColor: "hover:text-amber-300",
    icon: "🏛️"
  },
  AP: {
    id: "AP",
    name: "Andhra Pradesh",
    nameHindi: "ఆంధ్రప్రదేశ్ శాసనసభ • నమస్కారం",
    bgGradient: "bg-[#15803d]",
    heroGradient: "from-[#022c07] via-[#011402] to-[#000500]",
    bannerText: "🪙 Golden Hills of Tirumala Hills & Kuchipudi",
    primaryColor: "#15803d",
    buttonBg: "bg-yellow-405 text-neutral-900 hover:bg-yellow-350",
    accentBorder: "border-yellow-450",
    localGreeting: "ఆంధ్రప్రదేశ్ ప్రభుత్వ ఉద్యోగాలు",
    englishGreeting: "Namaskaram! Land of Amaravati & Tirupati Devotional Chants",
    culturalDescription: "Home to spectacular Tirupati hills, heritage Kuchipudi traditional dances, pristine Godavari river deltas, and Kondapalli terracotta toy crafts.",
    heritageMotif: "kathakali",
    tagBg: "bg-emerald-800",
    hoverTextColor: "hover:text-amber-300",
    icon: "🪙"
  },
  TG: {
    id: "TG",
    name: "Telangana",
    nameHindi: "తెలంగాణ ప్రాజెక్టులు • నమస్కారం",
    bgGradient: "bg-[#ea580c]",
    heroGradient: "from-[#451203] via-[#1a0500] to-[#080105]",
    bannerText: "🕌 Charminar Heritage Towers & Kakatiya Gateways",
    primaryColor: "#ea580c",
    buttonBg: "bg-yellow-300 text-slate-900 hover:bg-yellow-200",
    accentBorder: "border-yellow-400",
    localGreeting: "తెలంగాణ ఉద్యోగ విజ్ఞాన నిధి",
    englishGreeting: "Namaskaram! Welcome to Charminar and Bathukamma",
    culturalDescription: "Famous for the historic Charminar in Hyderabad, Kakatiya dynasty's stone gateways, Ramappa Temple (UNESCO), and the rich flower festival of Bathukamma.",
    heritageMotif: "india-gate",
    tagBg: "bg-yellow-600",
    hoverTextColor: "hover:text-yellow-300",
    icon: "🕌"
  },
  GJ: {
    id: "GJ",
    name: "Gujarat",
    nameHindi: "ગુજરાત સ્થાપત્ય • કેમ છો",
    bgGradient: "bg-[#ea580c]",
    heroGradient: "from-[#3a1001] via-[#0f0300] to-[#050000]",
    bannerText: "🎡 Land of Garba Beats, Sabarmati & Gir Lions",
    primaryColor: "#ea580c",
    buttonBg: "bg-white/90 text-slate-900 hover:bg-white",
    accentBorder: "border-white/50",
    localGreeting: "ગુજરાત સરકારી નોકરી ભરતી નિગમ",
    englishGreeting: "Kem Cho! Greetings from Sabarmati Ashram & Somnath",
    culturalDescription: "Vibrant land of traditional Dandiya-Garba circles, rich handloom Patola sarees, Dwarka marine heritage, and majestic Asiatic Lions of Gir forest.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-orange-500",
    hoverTextColor: "hover:text-amber-200",
    icon: "🎡"
  },
  KL: {
    id: "KL",
    name: "Kerala",
    nameHindi: "കേരള സംസ്കാരം തീം",
    bgGradient: "bg-[#065f46]",
    heroGradient: "from-[#043e2b] via-[#022015] to-[#01140d]",
    bannerText: "🌴 God's Own Country • Kerala State Culture & Jobs Dashboard",
    primaryColor: "#065f46",
    buttonBg: "bg-amber-550 text-white hover:bg-amber-500",
    accentBorder: "border-amber-300",
    localGreeting: "കേരള സർക്കാർ തൊഴിൽ അറിയിപ്പുകൾ",
    englishGreeting: "Swagatham! (സ്വാഗതം! - Welcome to Kerala)",
    culturalDescription: "Welcome to God's Own Country - Infused with traditional Kasavu golden borders, classical Kathakali elements, the lush coconut lagoons, Kalaripayattu heritage, and the celebrations of Onam.",
    heritageMotif: "kathakali",
    tagBg: "bg-emerald-600",
    hoverTextColor: "hover:text-amber-300",
    icon: "🌴"
  },
  PB: {
    id: "PB",
    name: "Punjab",
    nameHindi: "ਪੰਜਾਬ ਰਾਜ ਪੋਰਟਲ • ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    bgGradient: "bg-[#c2410c]",
    heroGradient: "from-[#3c1001] via-[#100300] to-[#050000]",
    bannerText: "🌾 Golden Temple Sanctuary & Bhangra Drum Beats",
    primaryColor: "#c2410c",
    buttonBg: "bg-yellow-400 text-slate-900 hover:bg-yellow-300",
    accentBorder: "border-yellow-400",
    localGreeting: "ਪੰਜਾਬ ਸਰਕਾਰੀ ਨੌਕਰੀਆਂ ਪ੍ਰभाग",
    englishGreeting: "Sat Sri Akal! Land of Five Rivers & Great Gurus",
    culturalDescription: "A glorious realm of positive energy, harvest celebrations, dhol drums, the golden spiritual towers of Amritsar Harmandir Sahib, and brave warriors.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-amber-600",
    hoverTextColor: "hover:text-yellow-300",
    icon: "🌾"
  },
  HR: {
    id: "HR",
    name: "Haryana",
    nameHindi: "हरियाणा लोक • राम राम",
    bgGradient: "bg-[#854d0e]",
    heroGradient: "from-[#2f1901] via-[#120700] to-[#060205]",
    bannerText: "🥛 Ancient Kurukshetra & Rich Milk Cattle Fields",
    primaryColor: "#854d0e",
    buttonBg: "bg-yellow-400 text-slate-900 hover:bg-yellow-300",
    accentBorder: "border-yellow-400",
    localGreeting: "हरियाणा शासकीय सेवा प्रभाग",
    englishGreeting: "Ram Ram! Land of Sacred Bhagavad Gita Sermon",
    culturalDescription: "Welcome to the brave land of incredible sports athletes, wrestling champions, dairy heritage, and historical battle memorials of Kurukshetra & Panipat.",
    heritageMotif: "india-gate",
    tagBg: "bg-yellow-750",
    hoverTextColor: "hover:text-amber-200",
    icon: "🥛"
  },
  OD: {
    id: "OD",
    name: "Odisha",
    nameHindi: "ଓଡ଼ିଶା ସଂସ୍କୃତି • ନମସ୍କାର",
    bgGradient: "bg-[#7c2d12]",
    heroGradient: "from-[#2c0b00] via-[#0f0000] to-[#050000]",
    bannerText: "☀️ Sacred Chariot of Lord Jagannath & Konark Wheel",
    primaryColor: "#7c2d12",
    buttonBg: "bg-yellow-400 text-[#7c2d12] hover:bg-yellow-300 font-extrabold",
    accentBorder: "border-yellow-400",
    localGreeting: "ଓଡ଼ିଶା ସରକାରୀ ଚାକିରି ପୋର୍ଟାଲ",
    englishGreeting: "Namaskar! Land of Lord Jagannath & Odissi Dance",
    culturalDescription: "Rich with pristine beaches, classical Odissi temple dances, the ancient stone carvings of Konark Sun Temple, and holy Puri Ratha Yatra processions.",
    heritageMotif: "alpana",
    tagBg: "bg-amber-800",
    hoverTextColor: "hover:text-yellow-300",
    icon: "☀️"
  },
  JH: {
    id: "JH",
    name: "Jharkhand",
    nameHindi: "झारखण्ड आदिवासी • जोहार",
    bgGradient: "bg-[#14532d]",
    heroGradient: "from-[#05220c] via-[#011405] to-[#000500]",
    bannerText: "🪵 Mineral Basin Hills & Sacred Deoghar Dhams",
    primaryColor: "#14532d",
    buttonBg: "bg-orange-500 text-white hover:bg-orange-400",
    accentBorder: "border-orange-400",
    localGreeting: "झारखण्ड कर्मचारी चयन आयोग पोर्टल",
    englishGreeting: "Johar! Cradle of Lord Baidyanath Jyotirlinga & Hills",
    culturalDescription: "Blessed with beautiful waterfalls of Ranchi, rich tribal culture of Santhal and Oraon communities, mineral basins, and divine Deoghar temples.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-[#14532d]",
    hoverTextColor: "hover:text-orange-300",
    icon: "🪵"
  },
  CG: {
    id: "CG",
    name: "Chhattisgarh",
    nameHindi: "छत्तीसगढ़ • जोहार",
    bgGradient: "bg-[#ca8a04]",
    heroGradient: "from-[#2e2203] via-[#100b00] to-[#050201]",
    bannerText: "🎨 Bastar Terracotta Bell Metal & Sirpur Temples",
    primaryColor: "#ca8a04",
    buttonBg: "bg-rose-700 text-white hover:bg-rose-600",
    accentBorder: "border-rose-500",
    localGreeting: "छत्तीसगढ़ व्यवसायिक लोक परीक्षा कार्यालय",
    englishGreeting: "Johar! Blessed by Bastar Dhokra Arts & Ancient sirpurs",
    culturalDescription: "Enjoy incredible tribal folklore, the spectacular Chitrakote mini-Niagara waterfalls, archaeological Sirpur monuments, and tribal brass crafts.",
    heritageMotif: "alpana",
    tagBg: "bg-yellow-700",
    hoverTextColor: "hover:text-rose-300",
    icon: "🎨"
  },
  AS: {
    id: "AS",
    name: "Assam",
    nameHindi: "অসম ৰাজ্য দ্বাৰ • নমস্কাৰ",
    bgGradient: "bg-[#1e3a1e]",
    heroGradient: "from-[#081e08] via-[#020d02] to-[#000500]",
    bannerText: "🌿 Mighty Brahmaputra, Kaziranga Rhinos & Camellias",
    primaryColor: "#1e3a1e",
    buttonBg: "bg-red-650 text-white hover:bg-red-550",
    accentBorder: "border-red-550",
    localGreeting: "অসম লোক সেৱা আয়োগ বতৰা",
    englishGreeting: "Rongali Bihu Greetings! Welcome to the Land of Sacred Kamakhya",
    culturalDescription: "Famous for lush green Assam tea gardens along the Brahmaputra, the rare One-Horned Rhino in Kaziranga National Park, and traditional Assamese silk *Muga* sarees.",
    heritageMotif: "alpana",
    tagBg: "bg-green-700",
    hoverTextColor: "hover:text-emerald-300",
    icon: "🌿"
  },
  JK: {
    id: "JK",
    name: "Jammu & Kashmir",
    nameHindi: "जम्मू और कश्मीर • आदाब",
    bgGradient: "bg-[#0c4a6e]",
    heroGradient: "from-[#031d2e] via-[#010c14] to-[#00050a]",
    bannerText: "❄️ Alpine Gulmarg Peaks & Shikaras in Dal Lake",
    primaryColor: "#0c4a6e",
    buttonBg: "bg-orange-500 text-white hover:bg-orange-400",
    accentBorder: "border-orange-400",
    localGreeting: "जम्मू कश्मीर शासकीय भर्ती परीक्षा मंडल",
    englishGreeting: "Adaab! Welcome to Paradise - Valley of Saffron & Kashmiri Chinar",
    culturalDescription: "Elegantly framing pristine Himalayan meadows, romantic Dal Lake shikaras, saffron gardens of Pampore, and magnificent Vaishno Devi shrines.",
    heritageMotif: "kathakali",
    tagBg: "bg-sky-800",
    hoverTextColor: "hover:text-amber-300",
    icon: "❄️"
  },
  UK: {
    id: "UK",
    name: "Uttarakhand",
    nameHindi: "उत्तराखंड देवभूमि • नमस्कार",
    bgGradient: "bg-[#1d4ed8]",
    heroGradient: "from-[#081f66] via-[#020a2e] to-[#00031a]",
    bannerText: "🗻 Devbhoomi Gateway - Char Dham Pilgrimages",
    primaryColor: "#1d4ed8",
    buttonBg: "bg-orange-500 text-white hover:bg-orange-400",
    accentBorder: "border-orange-400",
    localGreeting: "उत्तराखंड अधीनस्थ सेवा चयन केंद्र",
    englishGreeting: "Jai Badri Vishal! Warm Welcome to pristine Kedarnath-Badrinath",
    culturalDescription: "Surrounded by holy Ganga rapids of Rishikesh, towering Nanda Devi Himalayan snow lines, peaceful spiritual retreats, and ancient forests of Jim Corbett.",
    heritageMotif: "india-gate",
    tagBg: "bg-blue-800",
    hoverTextColor: "hover:text-orange-300",
    icon: "🗻"
  },
  HP: {
    id: "HP",
    name: "Himachal Pradesh",
    nameHindi: "हिमाचल प्रदेश • नमस्कार",
    bgGradient: "bg-[#0f766e]",
    heroGradient: "from-[#032e2b] via-[#011412] to-[#000707]",
    bannerText: "🍏 Solang Valley Meadows & Apple Orchard Groves",
    primaryColor: "#0f766e",
    buttonBg: "bg-yellow-400 text-teal-950 hover:bg-yellow-300 font-extrabold",
    accentBorder: "border-yellow-400",
    localGreeting: "हिमाचल प्रदेश लोक लोक परीक्षा परिषद",
    englishGreeting: "Namaste! Welcome to majestic Rohtang pass & Apple Valleys",
    culturalDescription: "The pure Himalayan escape filled with majestic deodar forests, Dharamshala spiritual monasteries, Shimla toy trains, and local Kullu woolen artistic works.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-teal-700",
    hoverTextColor: "hover:text-yellow-300",
    icon: "🍏"
  },
  TR: {
    id: "TR",
    name: "Tripura",
    nameHindi: "ত্রিপুরা রাজ্য • নমস্কাৰ",
    bgGradient: "bg-[#c2410c]",
    heroGradient: "from-[#401201] via-[#150400] to-[#050005]",
    bannerText: "🏯 Tripura Sundari Temple & Neermahal Lake Palace",
    primaryColor: "#c2410c",
    buttonBg: "bg-green-700 text-white hover:bg-green-600",
    accentBorder: "border-green-600",
    localGreeting: "ত্রিপুরা পাবলিক সার্ভিস কমিশন পঞ্জী",
    englishGreeting: "Khulumkha! Discover Unakoti rock reliefs & Bamboo Forests",
    culturalDescription: "Famed for spectacular historical architectures of Neermahal, ancient rock-cut reliefs of Unakoti, pure bamboo weavers, and rich ethnic customs.",
    heritageMotif: "alpana",
    tagBg: "bg-orange-800",
    hoverTextColor: "hover:text-yellow-350",
    icon: "🏯"
  },
  GA: {
    id: "GA",
    name: "Goa",
    nameHindi: "गोवा संस्कृति • नमस्कार",
    bgGradient: "bg-[#0284c7]",
    heroGradient: "from-[#01334f] via-[#001424] to-[#00050a]",
    bannerText: "🏖️ Sun, Sand, Mandovi River Cruises & Historic Chapora",
    primaryColor: "#0284c7",
    buttonBg: "bg-yellow-400 text-slate-900 hover:bg-yellow-300",
    accentBorder: "border-yellow-400",
    localGreeting: "गोवा राज्य शासकीय नोकरी माहिती विभाग",
    englishGreeting: "Dev Borem Karum! Welcome to Golden Beaches & Konkan Rhythms",
    culturalDescription: "Famous for gorgeous white sandy beaches, ancient Portuguese-style basilicas, fresh cashew plantations, dynamic carnival parades, and tranquil rivers.",
    heritageMotif: "kathakali",
    tagBg: "bg-sky-600",
    hoverTextColor: "hover:text-yellow-300",
    icon: "🏖️"
  },
  AR: {
    id: "AR",
    name: "Arunachal Pradesh",
    nameHindi: "अरुणाचल प्रदेश • नमस्कार",
    bgGradient: "bg-[#10b981]",
    heroGradient: "from-[#043323] via-[#01140d] to-[#000502]",
    bannerText: "🏔️ Land of Dawn-Lit Peaks & Tawang Orchid Monasteries",
    primaryColor: "#10b981",
    buttonBg: "bg-red-600 text-white hover:bg-red-500",
    accentBorder: "border-red-500",
    localGreeting: "अरुणाचल लोक शासकीय सेवा संघ",
    englishGreeting: "Tashi Delek! Welcome to the Soil of First Morning Sunbeams",
    culturalDescription: "The serene mountainous boundary hosting the spectacular Tawang Monastery, beautiful orchid reserve forests, and friendly Buddhist monasteries.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-emerald-600",
    hoverTextColor: "hover:text-amber-200",
    icon: "🏔️"
  },
  MN: {
    id: "MN",
    name: "Manipur",
    nameHindi: "मणिपुर संस्कृति • खुमूरंजरी",
    bgGradient: "bg-[#d946ef]",
    heroGradient: "from-[#3c0745] via-[#17011c] to-[#08000a]",
    bannerText: "🚣 Floating Phumdis on Loktak & Rare Sangai Deer",
    primaryColor: "#d946ef",
    buttonBg: "bg-indigo-650 text-white hover:bg-indigo-550",
    accentBorder: "border-indigo-550",
    localGreeting: "মণিপুর লোক সেবা আয়োগ বার্তা",
    englishGreeting: "Khurumjari! Greeting from the World's Only Floating Lagoon",
    culturalDescription: "Cradle of majestic Manipuri classical dances, the Loktak Lake floating islands *Phumdis*, rare Sangai deer, and birthplace of modern Polo.",
    heritageMotif: "alpana",
    tagBg: "bg-[#d946ef]",
    hoverTextColor: "hover:text-amber-300",
    icon: "🚣"
  },
  ML: {
    id: "ML",
    name: "Meghalaya",
    nameHindi: "मेघालय बादल • खुबलई",
    bgGradient: "bg-[#0d9488]",
    heroGradient: "from-[#032d29] via-[#011210] to-[#000505]",
    bannerText: "🌫️ Abode of Clouds & Living Forest Root Bridges",
    primaryColor: "#0d9488",
    buttonBg: "bg-amber-400 text-slate-900 hover:bg-amber-300",
    accentBorder: "border-amber-400",
    localGreeting: "মেঘালয় রাজ্য পাবলিক সার্ভিস কমিশন",
    englishGreeting: "Khublei! Beautiful Landscapes of Cherrapunji Forest Trails",
    culturalDescription: "The rainiest place on earth with gorgeous wild valleys, living tree root bridges, limestone caves, and matrilineal Khasi, Jaintia & Garo cultures.",
    heritageMotif: "kathakali",
    tagBg: "bg-teal-700",
    hoverTextColor: "hover:text-amber-300",
    icon: "🌫️"
  },
  NL: {
    id: "NL",
    name: "Nagaland",
    nameHindi: "नागालैंड हाइब्रिड • याके",
    bgGradient: "bg-[#b91c1c]",
    heroGradient: "from-[#3f0606] via-[#140101] to-[#050000]",
    bannerText: "🪶 Spectacular Hornbill Festivals & Naga Hills Heritage",
    primaryColor: "#b91c1c",
    buttonBg: "bg-amber-500 text-neutral-900 hover:bg-amber-400",
    accentBorder: "border-amber-500",
    localGreeting: "নাগালেণ্ড রাজকীয় চাকুরি প্রকোষ্ঠ",
    englishGreeting: "Yaake! Welcome to the Cradle of Traditional Warrior Clans",
    culturalDescription: "Celebrating the globally acclaimed Hornbill Festival, intricate tribal handwoven shawls, pristine Dzukou blooming valleys, and local music bands.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-[#b91c1c]",
    hoverTextColor: "hover:text-yellow-400",
    icon: "🪶"
  },
  MZ: {
    id: "MZ",
    name: "Mizoram",
    nameHindi: "मिज़ोरम • चियाबाई",
    bgGradient: "bg-[#0891b2]",
    heroGradient: "from-[#012f3b] via-[#001017] to-[#000508]",
    bannerText: "🥁 Blue Mountain Ridges & Bamboo Cheraw Festive Dances",
    primaryColor: "#0891b2",
    buttonBg: "bg-emerald-500 text-white hover:bg-emerald-450",
    accentBorder: "border-emerald-500",
    localGreeting: "মিজোরাম সরকারি চাকুরি বিজ্ঞপ্তি বোর্ড",
    englishGreeting: "Chibai! Cradle of Evergreen Hills and Chawngtlai Forts",
    culturalDescription: "Blessed with beautiful terraced hills, breathtaking bamboo Cheraw dance arrays, rich village custom tales, and lovely acoustic folk songs.",
    heritageMotif: "alpana",
    tagBg: "bg-cyan-700",
    hoverTextColor: "hover:text-emerald-300",
    icon: "🥁"
  },
  SK: {
    id: "SK",
    name: "Sikkim",
    nameHindi: "सिक्किम राज्य • टाशी देलेक",
    bgGradient: "bg-[#be185d]",
    heroGradient: "from-[#3c021a] via-[#140007] to-[#050002]",
    bannerText: "🏔️ Sacred Kanchenjunga Guardians & Monasteries",
    primaryColor: "#be185d",
    buttonBg: "bg-yellow-400 text-slate-900 hover:bg-yellow-300",
    accentBorder: "border-yellow-400",
    localGreeting: "சிக்கிம் மாநில அரசாங்க வேலையகங்கள்",
    englishGreeting: "Tashi Delek! Welcome to India's First Organic State Orchid Fields",
    culturalDescription: "Encounter majestic Buddhist prayer flags, the colossal cold peaks of Mount Kanchenjunga, beautiful glacial lakes, and traditional mask dances.",
    heritageMotif: "india-gate",
    tagBg: "bg-[#be185d]",
    hoverTextColor: "hover:text-yellow-300",
    icon: "🏔️"
  },
  CH: {
    id: "CH",
    name: "Chandigarh",
    nameHindi: "चंडीगढ़ प्रशासकीय • सत श्री अकाल",
    bgGradient: "bg-[#0f172a]",
    heroGradient: "from-[#1e293b] via-[#0f172a] to-[#020617]",
    bannerText: "📐 Iconic Rock Garden Sculptures & Le Corbusier Layouts",
    primaryColor: "#0f172a",
    buttonBg: "bg-emerald-550 text-white hover:bg-emerald-500",
    accentBorder: "border-emerald-500",
    localGreeting: "चंडीगढ़ भर्ती सूचना निदेशालय",
    englishGreeting: "Sat Sri Akal! Discover India’s Most Organized Smart City Circle",
    culturalDescription: "The modern aesthetic hub famous for legendary Rock Garden scrap stone monuments, peaceful Sukhna Lake, and perfectly designed tree lanes.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-slate-700",
    hoverTextColor: "hover:text-emerald-300",
    icon: "📐"
  },
  PY: {
    id: "PY",
    name: "Puducherry",
    nameHindi: "पुदुच्चेरी • बोनजोर",
    bgGradient: "bg-[#6366f1]",
    heroGradient: "from-[#1e1b4b] via-[#09052b] to-[#030114]",
    bannerText: "⚓ Peaceful French Quarter & Golden Globe Auroville",
    primaryColor: "#6366f1",
    buttonBg: "bg-yellow-400 text-slate-900 hover:bg-yellow-300",
    accentBorder: "border-[#bfdbfe]",
    localGreeting: "புதுச்சேரி அரசு வேலைவாய்ப்பு பதியங்கள்",
    englishGreeting: "Bonjour! Elegant Promenade Shorelines & Spiritual Centers",
    culturalDescription: "A lovely blend of ancient French-Indian architecture, golden domes of Auroville meditation center, mustard-colored villa streets, and ocean bays.",
    heritageMotif: "alpana",
    tagBg: "bg-indigo-700",
    hoverTextColor: "hover:text-yellow-300",
    icon: "⚓"
  },
  AN: {
    id: "AN",
    name: "Andaman & Nicobar",
    nameHindi: "अंडमान और निकोबार • नमस्कार",
    bgGradient: "bg-[#0e7490]",
    heroGradient: "from-[#083344] via-[#011420] to-[#00050c]",
    bannerText: "🐠 Coral Reef Islands, Radhanagar Bays & Historical Cellular Gate",
    primaryColor: "#0e7490",
    buttonBg: "bg-yellow-450 text-slate-905 hover:bg-yellow-350",
    accentBorder: "border-cyan-400",
    localGreeting: "अण्डमान तथा निकोबार शासकीय सूचना विभाग",
    englishGreeting: "Warm Welcome to the Emerald Sea Atolls in Indian Ocean",
    culturalDescription: "Surrounded by world-best Radhanagar pristine beaches, scuba coral reserves, and historic national memories of Cellular Jail sanctuary.",
    heritageMotif: "kathakali",
    tagBg: "bg-cyan-800",
    hoverTextColor: "hover:text-amber-300",
    icon: "🐠"
  },
  DN: {
    id: "DN",
    name: "Dadra & Nagar Haveli",
    nameHindi: "दादरा नगर हवेली",
    bgGradient: "bg-[#451a03]",
    heroGradient: "from-[#1c0800] via-[#080100] to-[#030005]",
    bannerText: "🪵 Silvassa Deer Sanctuaries & Tribal Warli Wall Art",
    primaryColor: "#451a03",
    buttonBg: "bg-amber-500 text-neutral-900 hover:bg-amber-400",
    accentBorder: "border-amber-400",
    localGreeting: "दादरा एवं नगर हवेली शासकीय अधिसूचना",
    englishGreeting: "Namaskar! Nestled in Lush green Western Ghat Valleys",
    culturalDescription: "Reflecting traditional Warli canvas drawings, silent deer forests along Vartak riverbanks, and lovely tribal wood carvings.",
    heritageMotif: "alpana",
    tagBg: "bg-amber-900",
    hoverTextColor: "hover:text-amber-200",
    icon: "🪵"
  },
  LA: {
    id: "LA",
    name: "Ladakh",
    nameHindi: "लद्दाख संस्कृत • जुले",
    bgGradient: "bg-[#4338ca]",
    heroGradient: "from-[#1e1b4b] via-[#09052b] to-[#020114]",
    bannerText: "🏔️ Pangong Tso Indigo Waters & Prayer Wheel Monasteries",
    primaryColor: "#4338ca",
    buttonBg: "bg-orange-500 text-white hover:bg-orange-400",
    accentBorder: "border-orange-400",
    localGreeting: "लद्दाख शासकीय स्वायत्त रोजगार सूचना",
    englishGreeting: "Julley! Welcome to the Roof of the World & High Mountain Passes",
    culturalDescription: "Steeped in mesmerizing Buddhist chants, stunning high-altitude cold deserts, sparkling Pangong Tso Lake, and historic copper metal arts.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-indigo-700",
    hoverTextColor: "hover:text-orange-300",
    icon: "🏔️"
  },
  LD: {
    id: "LD",
    name: "Lakshadweep",
    nameHindi: "लक्षद्वीप • अस्सलामु अलैकुम",
    bgGradient: "bg-[#0d9488]",
    heroGradient: "from-[#03302c] via-[#001010] to-[#000508]",
    bannerText: "⛵ Pristine Turquoise Lagoons & White Sandy Atolls",
    primaryColor: "#0d9488",
    buttonBg: "bg-yellow-400 text-teal-950 hover:bg-yellow-300 font-bold",
    accentBorder: "border-yellow-300",
    localGreeting: "ലക്ഷദ്വീപ് സർക്കാർ തൊഴിൽ നോട്ടിഫിക്കേഷൻ",
    englishGreeting: "Swagatham! Greetings from Scenic Coral Island Reefs",
    culturalDescription: "The tranquil archipelago of coconut groves, traditional sea boats, spectacular coral lagoons, and peaceful Island native folklore.",
    heritageMotif: "kathakali",
    tagBg: "bg-teal-700",
    hoverTextColor: "hover:text-yellow-300",
    icon: "⛵"
  },
  CI: {
    id: "CI",
    name: "Central Govt (All-India)",
    nameHindi: "अखिल भारतीय सरकारी नौकरियां • सत्यमेव जयते",
    bgGradient: "bg-[#cc0000]",
    heroGradient: "from-[#0d1544] via-[#050926] to-[#01020f]",
    bannerText: "🇮🇳 Authorized Central Commission Job Notifications",
    primaryColor: "#cc0000",
    buttonBg: "bg-amber-400 text-slate-950 hover:bg-amber-300",
    accentBorder: "border-amber-400",
    localGreeting: "सत्यमेव जयते • ऑल इंडिया रिक्रूटमेंट पोर्टल",
    englishGreeting: "Unified Union Ministry Jobs & Direct National Listings",
    culturalDescription: "Explore high-paying direct jobs in the Union Ministries of India, staff selection commissions, Railway Boards, Banking sectors, and Defense forces.",
    heritageMotif: "rotating-ashoka",
    tagBg: "bg-amber-400",
    hoverTextColor: "hover:text-amber-300",
    icon: "🇮🇳"
  }
};

export interface ThemeTranslations {
  latestJobs: string;
  latestJobsSub: string;
  freeAlerts: string;
  results: string;
  resultsSub: string;
  admitCards: string;
  admitCardsSub: string;
  stateGridTitle: string;
  stateGridSub: string;
  searchPlaceholder: string;
  categoriesTitle: string;
  categoriesSub: string;
  featuredTitle: string;
  searchButton: string;
}

export const TRANSLATIONS_DICTIONARY: Record<string, Partial<ThemeTranslations>> = {
  WB: {
    latestJobs: "🔥 সর্বশেষ সরকারি চাকরি বিজ্ঞপ্তি ২০২৬",
    latestJobsSub: "সরাসরি অফিসিয়াল ওয়েবসাইটে আবেদন করার যাচাইকৃত লিঙ্ক সহ রিয়েল-টাইম তালিকা",
    freeAlerts: "ফ্রি অ্যালার্ট পান 🔔",
    results: "💻 পরীক্ষা এবং ইন্টারভিউ ফলাফল",
    resultsSub: "সরাসরি লিঙ্ক সহ সাম্প্রতিক বোর্ড ও রেজাল্ট শিট",
    admitCards: "🎟️ পরীক্ষার অ্যাডমিট কার্ড / প্রবেশপত্র",
    admitCardsSub: "অনলাইন ডাউনলোড ও রিলিজ নোটিফিকেশন",
    stateGridTitle: "🗺️ রাজ্যভিত্তিক চাকরি এবং বিজ্ঞপ্তিসমূহ",
    stateGridSub: "আপনার পছন্দের রাজ্য এবং কেন্দ্রশাসিত অঞ্চল নির্বাচন করুন",
    searchPlaceholder: "পদ, বিভাগ বা যোগ্যতা দিয়ে খুঁজুন...",
    categoriesTitle: "⚡ চাকরির ক্যাটাগরি এবং দ্রুত অনুসন্ধান",
    categoriesSub: "যোগ্যতা এবং শূন্যপদের ধরন অনুসারে সাজানো",
    featuredTitle: "🌟 বিশিষ্ট নিয়োগ বিজ্ঞপ্তিসমূহ"
  },
  KL: {
    latestJobs: "🔥 ഏറ്റവും പുതിയ സർക്കാർ ജോലി അറിയിപ്പുകൾ 2026",
    latestJobsSub: "ഔദ്യോഗിക വെബ്സൈറ്റുകളിലേക്ക് തത്സമയ ലിങ്കുകളോടെ പരിശോധിച്ചുറപ്പിച്ചത്",
    freeAlerts: "സൗജന്യ അലേർട്ടുകൾ 🔔",
    results: "💻 പരീക്ഷാ ഫലങ്ങളും റാങ്ക് ലിസ്റ്റുകളും",
    resultsSub: "ഏറ്റവും പുതിയ പരീക്ഷാഫലങ്ങളും നേരിട്ടുള്ള ലിങ്കുകളും",
    admitCards: "🎟️ പരീക്ഷാ അഡ്മിറ്റ് കാർഡുകൾ ഔദ്യോഗികമായി",
    admitCardsSub: "ഡൗൺലോഡ് അറിയിപ്പുകൾ ഓൺലൈൻ വഴി",
    stateGridTitle: "🗺️ സംസ്ഥാനം തിരിച്ച് റിക്രൂട്ട്‌മെന്റ് തിരയുക",
    stateGridSub: "നിങ്ങളുടെ സംസ്ഥാനവും കേന്ദ്രഭരണ പ്രദേശങ്ങളും തിരഞ്ഞെടുക്കുക",
    searchPlaceholder: "തസ്തിക, ഇಲಾഖ അല്ലെങ്കിൽ യോഗ്യത വഴി തിരയുക...",
    categoriesTitle: "⚡ ജോലി വിഭാഗങ്ങളും ദ്രുത ലിങ്കുകളും",
    categoriesSub: "വിദ്യാഭ്യാസ യോഗ്യത അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക",
    featuredTitle: "🌟 മുൻനിര തൊഴിൽ അവസരങ്ങൾ"
  },
  TN: {
    latestJobs: "🔥 புதிய அரசு வேலைவாய்ப்பு அறிவிப்புகள் 2026",
    latestJobsSub: "நேரடி அதிகாரப்பூர்வ இணையதள விண்ணப்ப இணைப்புகளுடன் சரிபார்க்கப்பட்டது",
    freeAlerts: "இலவச அறிவிப்புகள் 🔔",
    results: "💻 தேர்வு முடிவுகள் & மதிப்பெண்கள்",
    resultsSub: "அண்மைய தேர்வு முடிவுகள் நேரடி இணைப்புகளுடன்",
    admitCards: "🎟️ தேர்வு நுழைவுச் சீட்டு (Admit Cards)",
    admitCardsSub: "தேர்வு நுழைவுச் சீட்டு பதிவிறக்கம் மற்றும் தேதிகள்",
    stateGridTitle: "🗺️ மாநில வாரியாக புதிய வேலைகள்",
    stateGridSub: "உங்களது மாநிலத்தை தேர்ந்தெடுத்து உடனே கண்டறியவும்",
    searchPlaceholder: "பதவி, துறை அல்லது தகுதியைத் தேடுங்கள்...",
    categoriesTitle: "⚡ வேலைப்பிரிவுகள் & விரைவு இணைப்புகள்",
    categoriesSub: "தகுதி மற்றும் காலியிட வகை வாரியாக தேடுங்கள்",
    featuredTitle: "🌟 சிறப்பு வேலைவாய்ப்புகள் மற்றும் அறிவிப்புகள்"
  },
  KA: {
    latestJobs: "🔥 ಇತ್ತೀಚಿನ ಸರ್ಕಾರಿ ಉದ್ಯೋಗ ಪ್ರಕಟಣೆಗಳು 2026",
    latestJobsSub: "ಅಧಿಕೃತ ವೆಬ್‌ಸೈಟ್‌ಗಳಿಗೆ ನೇರ ಲಿಂಕ್‌ಗಳೊಂದಿಗೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    freeAlerts: "ಉಚಿತ ಅಲರ್ಟ್ ಪ್ರಕಟಣೆಗಳು 🔔",
    results: "💻 ಪರೀಕ್ಷಾ ಫಲಿತಾಂಶಗಳು & ಅಂಕಪಟ್ಟಿಗಳು",
    resultsSub: "ಇತ್ತೀಚಿನ ಫಲಿತಾಂಶಗಳು ಮತ್ತು ನೇರ ಲಿಂಕ್‌ಗಳು",
    admitCards: "🎟️ ಪ್ರವೇಶ ಪತ್ರ ಹಾಗೂ ಪರೀಕ್ಷಾ ಮಂಡಳಿ",
    admitCardsSub: "ಪ್ರವೇಶ ಪತ್ರಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಇಲ್ಲಿ ನೋಡಿ",
    stateGridTitle: "🗺️ ರಾಜ್ಯವಾರು ಸರ್ಕಾರಿ ಉದ್ಯೋಗಗಳನ್ನು ಆರಿಸಿ",
    stateGridSub: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ರಾಜ್ಯ ಮತ್ತು ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳನ್ನು ಆರಿಸಿ",
    searchPlaceholder: "ಹುದ್ದೆ, ಇಲಾಖೆ ಅಥವಾ ವಿದ್ಯಾರ್ಹತೆ ಮೂಲಕ ಹುಡುಕಿ...",
    categoriesTitle: "⚡ ಉದ್ಯೋಗ ವಿಭಾಗಗಳು ಮತ್ತು ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
    categoriesSub: "ಅರ್ಹತೆ ಮತ್ತು ಹುದ್ದೆಯ ಪ್ರಕಾರ ವರ್ಗೀಕರಿಸಿ ಉದ್ಯೋಗ ಪಡೆಯಿರಿ",
    featuredTitle: "🌟 ಪ್ರಮುಖ ಉದ್ಯೋಗ ಪ್ರಕಟಣೆಗಳು"
  },
  AP: {
    latestJobs: "🔥 తాజా ప్రభుత్వ ఉద్యోగ నోటిఫికేషన్లు 2026",
    latestJobsSub: "అధికారిక వెబ్‌సైట్ ప్రత్యక్ష లింకులతో ధృవీకరించబడిన సమాచారం",
    freeAlerts: "ఉచిత అలర్ట్స్ పొందండి 🔔",
    results: "💻 పరీక్షా ఫలితాలు మరియు మెరిట్ లిస్ట్‌లు",
    resultsSub: "తాజా బోర్డులు మరియు కమిషన్ల ఫలితాలు",
    admitCards: "🎟️ హాల్ టికెట్లు మరియు వెబ్‌సైట్ లింకులు",
    admitCardsSub: "పరీక్షల కాల్ లెటర్ డౌన్‌లోడ్ సమాచారం",
    stateGridTitle: "🗺️ రాష్ట్రాల వారీగా తాజా ఉద్యోగాలు",
    stateGridSub: "మీ రాష్ట్రం ఆధారంగా ఉద్యోగాలను ఎంచుకోండి",
    searchPlaceholder: "పోస్టు, విభాగం లేదా అర్హతను వెతకండి...",
    categoriesTitle: "⚡ ఉద్యోగ విభాగాలు & త్వరిత లింకులు",
    categoriesSub: "విద్యార్హతలు మరియు ఖాళీల ఆధారంగా ఫిల్టర్ చేయండి",
    featuredTitle: "🌟 ప్రముఖ ప్రభుత్వ రిక్రూట్‌మెంట్లు"
  },
  TG: {
    latestJobs: "🔥 తాజా ప్రభుత్వ ఉద్యోగ నోటిఫికేషన్లు 2026",
    latestJobsSub: "అధికారిక వెబ్‌సైట్ ప్రత్యక్ష లింకులతో ధృవీకరించబడిన సమాచారం",
    freeAlerts: "ఉచిత అలర్ట్స్ పొందండి 🔔",
    results: "💻 పరీక్షా ఫలితాలు మరియు మెరిట్ లిస్ట్‌లు",
    resultsSub: "తాజా బోర్డులు మరియు కమిషన్ల ఫలితాలు",
    admitCards: "🎟️ హాల్ టికెట్లు మరియు వెబ్‌సైట్ లింకులు",
    admitCardsSub: "పరీక్షల కాల్ లెటర్ డౌన్‌లోడ్ సమాచారం",
    stateGridTitle: "🗺️ రాష్ట్రాల వారీగా తాజా ఉద్యోగాలు",
    stateGridSub: "మీ రాష్ట్రం ఆధారంగా ఉద్యోగాలను ఎంచుకోండి",
    searchPlaceholder: "పోస్టు, విభాగం లేదా అర్హతను వెతకండి...",
    categoriesTitle: "⚡ ఉద్యోగ విభాగాలు & త్వరిత లింకులు",
    categoriesSub: "విద్యార్హతలు మరియు ఖాళీల ఆధారంగా ఫిల్టర్ చేయండి",
    featuredTitle: "🌟 ప్రముఖ ప్రభుత్వ రిక్రూట్‌మెంట్లు"
  },
  GJ: {
    latestJobs: "🔥 નવીનતમ સરકારી નોકરી ભરતી અને જાહેરાતો 2026",
    latestJobsSub: "સત્તાવાર વેબસાઇટ લિંક્સ સાથે ચકાસાયેલ માહિતી",
    freeAlerts: "ફ્રી એલર્ટ મેળવો 🔔",
    results: "💻 પરીક્ષા પરિણામો અને ફાઇનલ લિસ્ટ",
    resultsSub: "વિવિધ બોર્ડ અને આયોગ દ્ધારા જાહેર પરિણામો",
    admitCards: "🎟️ પ્રવેશ પત્ર અને પરિક્ષા કોલ લેટર",
    admitCardsSub: "પરિક્ષા કોલ લેટર ડાઉનલોડ સીધી લિંક",
    stateGridTitle: "🗺️ રાજ્ય મુજબ નવી સરકારી નોકરીઓ",
    stateGridSub: "તમારા મનપસંદ રાજ્ય અને કેન્દ્રશાસિત પ્રદેશને પસંદ કરો",
    searchPlaceholder: "હોદ્દો, વિભાગ અથવા લાયકાત શોધો...",
    categoriesTitle: "⚡ ભરતી શ્રેણીઓ અને ત્વરિત લિંક્સ",
    categoriesSub: "લાયકાત અને ખાલી જગ્યા અનુસાર શોધો",
    featuredTitle: "🌟 મુખ્ય સરકારી ભરતી જાહેરાતો"
  },
  PB: {
    latestJobs: "🔥 ਨਵੀਨਤਮ ਸਰਕਾਰੀ ਨੌਕਰੀਆਂ 2026",
    latestJobsSub: "ਸਿੱਧੇ ਅਧਿਕਾਰਤ ਵੈੱਬਸਾਈਟ ਲਿੰਕਾਂ ਨਾਲ ਪ੍ਰਮਾਣਿਤ ਸੂਚੀਆਂ",
    freeAlerts: "ਮੁਫ਼ਤ ਅਲਰਟ ਪ੍ਰਾਪਤ ਕਰੋ 🔔",
    results: "💻 ਪ੍ਰੀਖਿਆ ਨਤੀਜੇ ਅਤੇ ਯੋਗ ਉਮੀਦਵਾਰ ਸੂਚੀ",
    resultsSub: "ਤਾਜ਼ਾ ਬੋਰਡ ਅਤੇ ਕਮਿਸ਼ਨ ਨਤੀਜੇ ਸਿੱਧੇ ਲਿੰਕਾਂ ਨਾਲ",
    admitCards: "🎟️ ਪ੍ਰਵੇਸ਼ ਪੱਤਰ ਅਤੇ ਰੋਲ ਨੰਬਰ ਸਲਿੱਪ",
    admitCardsSub: "ਐਡਮਿਟ ਕਾਰਡ ਡਾਊਨਲੋਡ ਲਿੰਕ ਸਰਗਰਮ",
    stateGridTitle: "🗺️ ਰਾਜ ਅਨੁਸਾਰ ਸਰਕਾਰੀ ਭਰਤੀ ਖੋਜੋ",
    stateGridSub: "ਆਪਣੇ ਪਸੰਦੀਦਾ ਰਾਜ ਦੀ ਚੋਣ ਕਰੋ",
    searchPlaceholder: "ਪੋਸਟ, ਵਿਭਾਗ ਜਾਂ ਯੋਗਤਾ ਮੁਤਾਬਕ ਲੱਭੋ...",
    categoriesTitle: "⚡ ਨੌਕਰੀ ਸ਼੍ਰੇਣੀਆਂ ਅਤੇ ਤੁਰੰਤ ਲਿੰਕ",
    categoriesSub: "ਵਿਦਿਅਕ ਯੋਗਤਾ ਮੁਤਾਬਕ ਫਿਲਟਰ ਕਰੋ",
    featuredTitle: "🌟 ਮੁੱਖ ਭਰਤੀ ਪ੍ਰਦਰਸ਼ਨ ਅਤੇ ਅਪਡੇਟਸ"
  },
  OD: {
    latestJobs: "🔥 ସଦ୍ୟତମ ସରକାରୀ ଚାକିରି ବିଜ୍ଞପ୍ତି ୨୦ souvenir",
    latestJobsSub: "ସିଧାସଳଖ ଅଫିସିଆଲ୍ ୱେବସਾਈଟ୍ ଆବੇଦନ ଲିଙ୍କ୍ ର ଶୃଙ୍ଖଳା",
    freeAlerts: "ମାଗଣା ଚାକିରି ଆଲର୍ଟ 🔔",
    results: "💻 ପରୀକ୍ଷା ଫଳାଫଳ ଏବଂ ସିଲେକ୍ସନ ଲିଷ୍ଟ",
    resultsSub: "ସଦ୍ୟ ପ୍ରକାଶିତ ବୋର୍ଡ ଏବଂ କମिଶନ ପରୀକ୍ଷା ଫଳ",
    admitCards: "🎟️ ପ୍ରବେଶ ପତ୍ର ପରୀକ୍ଷା ଆଡମିଟ୍ କାର୍ଡ",
    admitCardsSub: "ପରୀକ୍ଷା ଆଡମିଟ୍ କାର୍ଡ ସିଧାସଳଖ ଡାଉନଲୋଡ୍",
    stateGridTitle: "🗺️ ରାଜ୍ୟ ଅନୁସାରେ ନୂତନ ଚାକିରି ଖୋଜନ୍ତು",
    stateGridSub: "ଆପଣଙ୍କ ରାଜ୍ୟ କିମ୍ବା କେନ୍ଦ୍ରଶାସିତ ଅଞ୍ചଳ ଚୟନ କରନ୍ତು",
    searchPlaceholder: "ପଦଵୀ, ବିଭାଗ କିମ୍ବା ଯୋଗ୍ୟତା ଲେଖି ଖୋଜନ୍ତু...",
    categoriesTitle: "⚡ ବିଭିନ୍ன ବିଭାଗ ଏବଂ ଶୀଘ្រ ଲିଙ୍କ୍",
    categoriesSub: "ଶିକ୍ษาଗତ ଯୋଗ୍ୟତା ଏବଂ ପଦଵୀ ଅନୁଯାୟୀ ତାଲିକା",
    featuredTitle: "🌟 ବିଶେଷ ନିଯୁକ୍ତି ପ୍ରକ୍ରିୟା"
  },
  AS: {
    latestJobs: "🔥 শেহতীয়া চৰকাৰী চাকৰিৰ খবৰ ২০২৬",
    latestJobsSub: "পোনপটীয়া চৰকাৰী লিংকৰ সৈতে প্ৰমাণিত তালিকা",
    freeAlerts: "ফ্ৰী এলাৰ্ট লাভ কৰক 🔔",
    results: "💻 পৰীক্ষাৰ ফলাফলসমূহ পোনপটীয়াকৈ",
    resultsSub: " শেহতীয়া পৰীক্ষাৰ ফলাফল আৰু পোনপটীয়া লিংকসমূহ",
    admitCards: "🎟️ এডমিট কাৰ্ড আৰু প্ৰৱেশ পত্ৰসমূহ",
    admitCardsSub: "পৰীক্ষাৰ প্ৰৱেশ পত্ৰ ডাউনলোড কৰক ইয়াত",
    stateGridTitle: "🗺️ ৰাজ্য অনুসৰি চৰকাৰী চাকৰি বিচাৰক",
    stateGridSub: "আপোনাৰ প্ৰিয় ৰাজ্যখন বাছনি কৰক আৰু আবেদন কৰক",
    searchPlaceholder: "পদ, বিভাগ বা অৰ্হতা অনুযায়ী অনুসন্ধান কৰক...",
    categoriesTitle: "⚡ চাকৰিৰ শ্ৰেনী আৰু ক্ষীপ্ৰ লিংক",
    categoriesSub: "অৰ্হতা আৰু খালী পদৰ ধৰণ অনুসৰি বাছক",
    featuredTitle: "🌟 বিশেষ নিযুক্তি জাননী আৰু বিজ্ঞাপন"
  }
};

export const DEFAULT_HINDI_TRANSLATION: ThemeTranslations = {
  latestJobs: "🔥 नवीनतम सरकारी नौकरी सूचनाएं 2026",
  latestJobsSub: "सीधे आधिकारिक वेबसाइट आवेदन लिंक के साथ सत्यापित सूचियां",
  freeAlerts: "फ्री अलार्म और जॉब अलर्ट 🔔",
  results: "💻 परीक्षा परिणाम (Sarkari Results)",
  resultsSub: "सीधे लिंक के साथ हालिया बोर्ड और आयोग परिणाम पत्रक",
  admitCards: "🎟️ प्रवेश पत्र (Admit Cards) डाउनलोड",
  admitCardsSub: "नवीनतम परीक्षा कॉल लेटर डाउनलोड करें",
  stateGridTitle: "🗺️ राज्य अनुसार नौकरियां खोजें",
  stateGridSub: "अपने मनपसंद राज्य और केंद्र शासित प्रदेश को चुनें",
  searchPlaceholder: "पद, विभाग या योग्यता खोजें...",
  categoriesTitle: "⚡ नौकरी श्रेणियां और त्वरित लिंक",
  categoriesSub: "शैक्षणिक योग्यता और भर्ती श्रेणियों के अनुसार खोजें",
  featuredTitle: "🌟 मुख्य भर्ती विज्ञापन",
  searchButton: "खोजें"
};

export function getTranslations(themeId: CultureThemeId): ThemeTranslations {
  const dictionary = TRANSLATIONS_DICTIONARY[themeId] || {};
  return {
    latestJobs: dictionary.latestJobs || DEFAULT_HINDI_TRANSLATION.latestJobs,
    latestJobsSub: dictionary.latestJobsSub || DEFAULT_HINDI_TRANSLATION.latestJobsSub,
    freeAlerts: dictionary.freeAlerts || DEFAULT_HINDI_TRANSLATION.freeAlerts,
    results: dictionary.results || DEFAULT_HINDI_TRANSLATION.results,
    resultsSub: dictionary.resultsSub || DEFAULT_HINDI_TRANSLATION.resultsSub,
    admitCards: dictionary.admitCards || DEFAULT_HINDI_TRANSLATION.admitCards,
    admitCardsSub: dictionary.admitCardsSub || DEFAULT_HINDI_TRANSLATION.admitCardsSub,
    stateGridTitle: dictionary.stateGridTitle || DEFAULT_HINDI_TRANSLATION.stateGridTitle,
    stateGridSub: dictionary.stateGridSub || DEFAULT_HINDI_TRANSLATION.stateGridSub,
    searchPlaceholder: dictionary.searchPlaceholder || DEFAULT_HINDI_TRANSLATION.searchPlaceholder,
    categoriesTitle: dictionary.categoriesTitle || DEFAULT_HINDI_TRANSLATION.categoriesTitle,
    categoriesSub: dictionary.categoriesSub || DEFAULT_HINDI_TRANSLATION.categoriesSub,
    featuredTitle: dictionary.featuredTitle || DEFAULT_HINDI_TRANSLATION.featuredTitle,
    searchButton: dictionary.searchButton || DEFAULT_HINDI_TRANSLATION.searchButton,
  };
}

export function getTheme(idOrName: string): CultureThemeConfig {
  if (!idOrName) return CULTURE_THEMES.national;
  
  const normalized = idOrName.trim().toUpperCase();
  
  // Try exact state code match first
  if (CULTURE_THEMES[normalized]) {
    return CULTURE_THEMES[normalized];
  }
  
  // Try case-insensitive substring search in descriptive fields/names
  const found = Object.values(CULTURE_THEMES).find(t => 
    t.name.toUpperCase().includes(normalized) || 
    normalized.includes(t.name.toUpperCase()) ||
    t.nameHindi.toUpperCase().includes(normalized)
  );
  
  return found || CULTURE_THEMES.national;
}
