import { Job, ExamResult, AdmitCard, SiteSettings } from "./types";

export interface StateCard {
  name: string;
  short: string;
}

export const STATE_CARDS: StateCard[] = [
  { name: "Andhra Pradesh", short: "AP" },
  { name: "Arunachal Pradesh", short: "AR" },
  { name: "Assam", short: "AS" },
  { name: "Bihar", short: "BR" },
  { name: "Chhattisgarh", short: "CG" },
  { name: "Goa", short: "GA" },
  { name: "Gujarat", short: "GJ" },
  { name: "Haryana", short: "HR" },
  { name: "Himachal Pradesh", short: "HP" },
  { name: "Jharkhand", short: "JH" },
  { name: "Karnataka", short: "KA" },
  { name: "Kerala", short: "KL" },
  { name: "Madhya Pradesh", short: "MP" },
  { name: "Maharashtra", short: "MH" },
  { name: "Manipur", short: "MN" },
  { name: "Meghalaya", short: "ML" },
  { name: "Mizoram", short: "MZ" },
  { name: "Nagaland", short: "NL" },
  { name: "Odisha", short: "OD" },
  { name: "Punjab", short: "PB" },
  { name: "Rajasthan", short: "RJ" },
  { name: "Sikkim", short: "SK" },
  { name: "Tamil Nadu", short: "TN" },
  { name: "Telangana", short: "TG" },
  { name: "Tripura", short: "TR" },
  { name: "Uttar Pradesh", short: "UP" },
  { name: "Uttarakhand", short: "UK" },
  { name: "West Bengal", short: "WB" },
  // Union Territories
  { name: "Andaman & Nicobar", short: "AN" },
  { name: "Chandigarh", short: "CH" },
  { name: "Dadra & Nagar Haveli", short: "DN" },
  { name: "Daman & Diu", short: "DD" },
  { name: "Delhi", short: "DL" },
  { name: "Jammu & Kashmir", short: "JK" },
  { name: "Ladakh", short: "LA" },
  { name: "Lakshadweep", short: "LD" },
  { name: "Puducherry", short: "PY" }
];

export const JOB_CATS = [
  "Central Government",
  "State Government",
  "Railway Jobs",
  "Banking Jobs",
  "SSC Jobs",
  "UPSC Jobs",
  "Defence Jobs",
  "Police Jobs",
  "Teaching Jobs",
  "Engineering Jobs",
  "Medical Jobs",
  "ITI/Diploma Jobs",
  "Apprentice Jobs",
  "PSU Jobs",
  "India Post",
  "Judiciary Jobs",
  "Research & Science"
];

export const QUALS = [
  "8th Pass",
  "10th Pass",
  "12th Pass",
  "ITI",
  "Diploma",
  "Graduate",
  "B.Sc",
  "B.Com",
  "B.A",
  "B.Tech/B.E",
  "MBBS",
  "B.Ed",
  "LLB",
  "Post Graduate",
  "M.Tech",
  "PhD",
  "As per Notification"
];

export const CAT_COLORS: Record<string, string> = {
  "SSC Jobs": "#e02424",       // Red
  "Railway Jobs": "#0e9f6e",   // Green
  "Banking Jobs": "#1a56db",   // Blue
  "Police Jobs": "#e3a008",    // Amber/Yellow
  "UPSC Jobs": "#7e3af2",      // Purple
  "Teaching Jobs": "#057a55",  // Dark Green
  "Central Government": "#3b82f6",
  "State Government": "#ec4899",
  "Defence Jobs": "#111827",
  "Engineering Jobs": "#06b6d4",
  "Medical Jobs": "#f43f5e",
  "ITI/Diploma Jobs": "#8b5cf6",
  "Apprentice Jobs": "#f97316",
  "PSU Jobs": "#6b7280",
  "India Post": "#f59e0b",
  "Judiciary Jobs": "#4f46e5",
  "Research & Science": "#10b981"
};

export const INIT_JOBS: Job[] = [
  {
    id: 1001,
    title: "SSC CGL 2025 Online Application",
    org: "Staff Selection Commission (SSC)",
    category: "SSC Jobs",
    state: "All India",
    vacancy: "17,727",
    lastDate: "2025-06-15",
    qual: "Graduate",
    salary: "₹25,500 – ₹1,51,100 per month (Level-4 to Level-8 Pay Matrix)",
    fee: "₹100",
    feeSC: "Free",
    feeFemale: "Free",
    ageLow: "18",
    ageHigh: "32",
    applyLink: "https://ssc.gov.in",
    notifLink: "https://ssc.gov.in/api/notification",
    status: "active",
    isHot: true,
    isNew: true,
    desc: "Staff Selection Commission (SSC) has released the statutory handbook notification for Combined Graduate Level (CGL) Examination 2025. This premier recruitment drive is intended to fill up 17,727 vacant Assistant Section Officer, Inspector, Auditor, and Executive Assistant roles inside national state ministries, departments, and statutory bodies of the Government of India.",
    created: "2026-05-29T10:00:00Z"
  },
  {
    id: 1002,
    title: "UP Police Constable Recruitment 2025",
    org: "Uttar Pradesh Police Recruitment & Promotion Board (UPPRPB)",
    category: "Police Jobs",
    state: "Uttar Pradesh",
    vacancy: "60,244",
    lastDate: "2025-06-30",
    qual: "12th Pass",
    salary: "₹21,700 – ₹69,100 per month (Grade Pay ₹2,000)",
    fee: "₹400",
    feeSC: "₹400",
    feeFemale: "₹400",
    ageLow: "18",
    ageHigh: "25",
    applyLink: "https://uppbpb.gov.in",
    notifLink: "https://uppbpb.gov.in/notifications",
    status: "active",
    isHot: true,
    isNew: true,
    desc: "Uttar Pradesh Police Recruitment and Promotion Board (UPPRPB) invites qualified applicants to enlist for Constable Civil Police posts. With over 60,244 positions open under the regulatory authority, physical fitness assessments and written exams will be planned for selected competitors in multiple state centers.",
    created: "2026-05-29T11:00:00Z"
  },
  {
    id: 1003,
    title: "India Post Gramin Dak Sevak (GDS) Cycle-8",
    org: "Department of Posts, India Post",
    category: "India Post",
    state: "All India",
    vacancy: "35,500",
    lastDate: "2025-06-10",
    qual: "10th Pass",
    salary: "₹12,000 – ₹29,380 per month (depending on designation Branch Postmaster / Assistant BPM)",
    fee: "₹100",
    feeSC: "Free",
    feeFemale: "Free",
    ageLow: "18",
    ageHigh: "40",
    applyLink: "https://indiapostgdsonline.gov.in",
    notifLink: "https://indiapostgdsonline.gov.in/pdf",
    status: "active",
    isHot: false,
    isNew: true,
    desc: "India Post has launched global circular applications for Gramin Dak Sevaks (GDS), Branch Postmasters (BPM), and Assistant Branch Postmasters (ABPM) for the current financial cycle. The shortlisting will be prepared through automatic computerized selection lists based on standard 10th standard board percentage matrices with no written examination.",
    created: "2026-05-28T09:00:00Z"
  },
  {
    id: 1004,
    title: "RRB NTPC Graduate Level Recruitment Exam",
    org: "Railway Recruitment Boards (RRB)",
    category: "Railway Jobs",
    state: "All India",
    vacancy: "11,558",
    lastDate: "2025-07-15",
    qual: "Graduate",
    salary: "₹19,900 – ₹35,400 per month (initial level basic scaling)",
    fee: "₹500",
    feeSC: "₹250 (Refundable after Tier-1 Exam)",
    feeFemale: "₹250 (Refundable after Tier-1 Exam)",
    ageLow: "18",
    ageHigh: "36",
    applyLink: "https://rrbcdg.gov.in",
    notifLink: "https://rrbcdg.gov.in/ntpc-details",
    status: "active",
    isHot: true,
    isNew: false,
    desc: "Ministry of Railways (Railway Board) announces competitive Computer-Based Written Assessments (CBTs) for recruiters seeking lucrative roles in Commercial Apprentices, Goods Train Managers, Station Masters, Senior Clerks, and Junior Accounts Assistants across regional Indian Railway zones.",
    created: "2026-05-27T08:00:00Z"
  },
  {
    id: 1005,
    title: "SBI Junior Associates (Clerical Grade) 2025",
    org: "State Bank of India (SBI)",
    category: "Banking Jobs",
    state: "All India",
    vacancy: "8,283",
    lastDate: "2025-05-25",
    qual: "Graduate",
    salary: "₹17,900 – ₹47,920 per month (with multiple central DA & allowances package)",
    fee: "₹750",
    feeSC: "Free",
    feeFemale: "Free",
    ageLow: "20",
    ageHigh: "28",
    applyLink: "https://sbi.co.in/careers",
    notifLink: "https://sbi.co.in/web/careers/current-openings",
    status: "active",
    isHot: false,
    isNew: false,
    desc: "State Bank of India (SBI) invites registrations for Clerk positions (Junior Associates - Customer Support & Sales) across regional state branches. Selection will be purely structured through subsequent Preliminary and Mains computer evaluations, paired with local language eligibility tests.",
    created: "2026-05-26T14:00:00Z"
  },
  {
    id: 1006,
    title: "UPSC Civil Services Examination (Pre) 2025",
    org: "Union Public Service Commission (UPSC)",
    category: "UPSC Jobs",
    state: "All India",
    vacancy: "1,056",
    lastDate: "2025-04-12",
    qual: "Graduate",
    salary: "₹56,100 – ₹2,50,050 per month (Level-10 in Central Civil Cadre Matrix)",
    fee: "₹100",
    feeSC: "Free",
    feeFemale: "Free",
    ageLow: "21",
    ageHigh: "32",
    applyLink: "https://upsconline.nic.in",
    notifLink: "https://upsc.gov.in",
    status: "expired",
    isHot: false,
    isNew: false,
    desc: "Union Public Service Commission (UPSC) Civil Services (IAS/IFS/IPS) Entrance exams notification. Selected candidates earn standard prestigious positions in state administrative services under high advisory capacities.",
    created: "2026-05-25T10:00:00Z"
  },
  {
    id: 1007,
    title: "WB Police Constable Notification 2026",
    org: "West Bengal Police Recruitment Board (WBPRB)",
    category: "Police Jobs",
    state: "West Bengal",
    vacancy: "11,200",
    lastDate: "2026-06-30",
    qual: "10th Pass",
    salary: "₹22,700 – ₹58,500 per month (Pay Band 2 + allowances)",
    fee: "₹170",
    feeSC: "₹20",
    feeFemale: "₹20",
    ageLow: "18",
    ageHigh: "30",
    applyLink: "https://prb.wb.gov.in",
    notifLink: "https://prb.wb.gov.in/notifications",
    status: "active",
    isHot: true,
    isNew: true,
    desc: "West Bengal Police Recruitment Board (WBPRB / WB Police) invites online applications for recruitment of General Duty Constable posts in West Bengal Police Force. Eligible candidates with Madhyamik/10th pass qualification can submit applications securely before the deadline.",
    created: "2026-05-29T12:00:00Z"
  },
  {
    id: 1008,
    title: "WBPSC Clerkship Examination 2026 Active Forms",
    org: "West Bengal Public Service Commission (WBPSC)",
    category: "Teaching Jobs",
    state: "West Bengal",
    vacancy: "6,000",
    lastDate: "2026-07-15",
    qual: "12th Pass",
    salary: "₹22,700 – ₹58,500 (Level 6 Pay Matrix)",
    fee: "₹110",
    feeSC: "Free",
    feeFemale: "Free",
    ageLow: "18",
    ageHigh: "40",
    applyLink: "https://psc.wb.gov.in",
    notifLink: "https://psc.wb.gov.in/pdf",
    status: "active",
    isHot: true,
    isNew: true,
    desc: "Detailed official bulletin declared by West Bengal Public Service Commission (WBPSC) for recruitment of Lower Division Assistant (LDA), Lower Division Clerk (LDC), or equivalent posts across administrative Directorates and District Offices of the Government of West Bengal.",
    created: "2026-05-29T13:00:00Z"
  },
  {
    id: 1009,
    title: "Bihar Police Constable Vacancies recruitment 2026",
    org: "Central Selection Board of Constables (CSBC), Bihar",
    category: "Police Jobs",
    state: "Bihar",
    vacancy: "24,000",
    lastDate: "2026-06-25",
    qual: "12th Pass",
    salary: "₹21,700 – ₹69,100 per month State scale",
    fee: "₹675",
    feeSC: "₹180",
    feeFemale: "₹180",
    ageLow: "18",
    ageHigh: "25",
    applyLink: "https://csbc.bih.nic.in",
    notifLink: "https://csbc.bih.nic.in/notifications",
    status: "active",
    isHot: true,
    isNew: true,
    desc: "Central Board of Constables Bihar (CSBC / Bihar Police) releases direct recruitment selection rules for 24,000 vacant Constable positions. Physical standards testing (PST/PET) combined with written merit indexes compose selection guidelines.",
    created: "2026-05-29T14:45:00Z"
  },
  {
    id: 1010,
    title: "BPSC 71st Combined Competitive Entrance Exam",
    org: "Bihar Public Service Commission (BPSC)",
    category: "UPSC Jobs",
    state: "Bihar",
    vacancy: "850",
    lastDate: "2026-07-10",
    qual: "Graduate",
    salary: "₹53,100 – ₹1,67,800 Group A Pay Scaling",
    fee: "₹600",
    feeSC: "₹150",
    feeFemale: "₹150",
    ageLow: "21",
    ageHigh: "37",
    applyLink: "https://bpsc.bih.nic.in",
    notifLink: "https://bpsc.bih.nic.in/pdf",
    status: "active",
    isHot: false,
    isNew: true,
    desc: "Bihar Public Service Commission (BPSC) announces preliminary screening exam procedures for administrative cadre postings (SDM, DSP, Revenue Officer, Block Panchayat Officer) inside Bihar Civil Services departments.",
    created: "2026-05-29T15:30:00Z"
  },
  {
    id: 1011,
    title: "WB Health GDMO General Duty Medical Officers Recruitment",
    org: "West Bengal Health Recruitment Board (WBHRB / WB Health)",
    category: "Medical Jobs",
    state: "West Bengal",
    vacancy: "1,500",
    lastDate: "2026-06-18",
    qual: "MBBS",
    salary: "₹56,100 – ₹1,44,300 Level-16 pay scale",
    fee: "₹210",
    feeSC: "Free",
    feeFemale: "Free",
    ageLow: "22",
    ageHigh: "36",
    applyLink: "https://hrb.wb.gov.in",
    notifLink: "https://hrb.wb.gov.in/notifications",
    status: "active",
    isHot: false,
    isNew: false,
    desc: "West Bengal Health Recruitment Board (WB Health) announces selection matrices for MBBS medical professionals seeking permanent clinical roles in West Bengal Medical Services (WBMS) across public health networks.",
    created: "2026-05-28T12:00:00Z"
  },
  {
    id: 1012,
    title: "WBSSC Upper Primary Teacher and Group-C Selection Merit",
    org: "West Bengal School Service Commission (WBSSC)",
    category: "Teaching Jobs",
    state: "West Bengal",
    vacancy: "4,500",
    lastDate: "2026-07-20",
    qual: "Graduate",
    salary: "₹32,100 - ₹82,900 state matrix scale",
    fee: "₹250",
    feeSC: "₹100",
    feeFemale: "₹100",
    ageLow: "20",
    ageHigh: "40",
    applyLink: "https://westbengalssc.com",
    notifLink: "https://westbengalssc.com/notices",
    status: "active",
    isHot: false,
    isNew: false,
    desc: "West Bengal School Service Commission (WBSSC) updates teacher evaluation standards for Upper Primary classes and clerical Group-C staff allocations across government sponsored senior secondary schools.",
    created: "2026-05-27T15:00:00Z"
  }
];

export const INIT_RESULTS: ExamResult[] = [
  {
    id: 2001,
    title: "SSC CHSL Tier-I Exam Result 2024",
    exam: "Combined Higher Secondary Level 2024",
    date: "2026-05-28",
    link: "https://ssc.gov.in/results",
    state: "All India",
    status: "published"
  },
  {
    id: 2005,
    title: "WB Police Constable Written Exam merit list criteria",
    exam: "WB Police Constable Civilian annual selection list",
    date: "2026-05-30",
    link: "https://prb.wb.gov.in/results",
    state: "West Bengal",
    status: "published"
  },
  {
    id: 2006,
    title: "WBJEE Merit Ranking list and Category Cut-off",
    exam: "West Bengal Joint Entrance Engineering Examination (WBJEE)",
    date: "2026-05-26",
    link: "https://wbjeeb.nic.in",
    state: "West Bengal",
    status: "published"
  },
  {
    id: 2007,
    title: "Bihar Board Class XII Revised Intermediate Result Tracker",
    exam: "BSEB class XII Annual Board Exam Results",
    date: "2026-05-29",
    link: "http://biharboardonline.bihar.gov.in",
    state: "Bihar",
    status: "published"
  },
  {
    id: 2002,
    title: "UP Police Constable Written Exam Merit List",
    exam: "Constable Civilian Recruitment 2024 Exam",
    date: "2026-05-29",
    link: "https://uppbpb.gov.in/constable-results",
    state: "Uttar Pradesh",
    status: "published"
  },
  {
    id: 2003,
    title: "Bihar Board 10th Intermediate Examination Results",
    exam: "BSEB Class X Annual Board Exams",
    date: "2026-05-20",
    link: "http://results.biharboardonline.com",
    state: "Bihar",
    status: "published"
  },
  {
    id: 2004,
    title: "NTA CUET UG Entrance Checked Scorecards 2025",
    exam: "Common University Entrance Test Undergraduate",
    date: "2026-05-25",
    link: "https://cuetug.ntaonline.in",
    state: "All India",
    status: "published"
  }
];

export const INIT_ADMITS: AdmitCard[] = [
  {
    id: 3001,
    title: "UPSC Civil Services IAS Prelims Hall Ticket 2025",
    exam: "Civil Services Preliminary Screening Test",
    examDate: "2025-06-12",
    link: "https://upsconline.nic.in/admit-card",
    state: "All India",
    status: "published"
  },
  {
    id: 3005,
    title: "WB Police Constable Physical PET/PMT Admit Card 2026",
    exam: "WB Police Physical Test Screening Pass",
    examDate: "2026-06-10",
    link: "https://prb.wb.gov.in/download-admit",
    state: "West Bengal",
    status: "published"
  },
  {
    id: 3006,
    title: "WBPSC Clerkship Written Entrance Admission Pass 2026",
    exam: "WB Civil Clerkship Competitive Examination",
    examDate: "2026-07-02",
    link: "https://psc.wb.gov.in/admit",
    state: "West Bengal",
    status: "published"
  },
  {
    id: 3007,
    title: "BPSC Teacher TRE Phase 3 Re-exam Hall Ticket",
    exam: "Bihar Teacher Recruitment Competitive Written Assessment",
    examDate: "2026-06-15",
    link: "https://bpsc.bih.nic.in/admit-download",
    state: "Bihar",
    status: "published"
  },
  {
    id: 3002,
    title: "RRB Group D Tier-1 Written Examination Gate Pass",
    exam: "Railway Group D Trackman Recruitment 2025",
    examDate: "2025-07-20",
    link: "https://rrbcdg.gov.in/admit_cards",
    state: "All India",
    status: "published"
  },
  {
    id: 3003,
    title: "SSC GD Constable Regional PST/PET Call Letter",
    exam: "General Duty Constable Physical Eligibility Ground Pass",
    examDate: "2025-06-15",
    link: "https://ssc.gov.in/download-admit-card",
    state: "All India",
    status: "published"
  },
  {
    id: 3004,
    title: "IBPS PO Phase-I Preliminary Exam Admit Card 2025",
    exam: "Probationary Officers Online Examination",
    examDate: "2025-06-05",
    link: "https://ibps.in",
    state: "All India",
    status: "published"
  }
];

export const DEFAULT_TICKER = "🚨 Latest Update: SSC CGL 2025 Combined Graduate Level Online forms are active til 15-June-2025. Apply now! | UP Police Constable Recruitment 60,244 vacancies last date extended to 30-June-2025. | Download UPSC IAS Civils Admission passes now. | Bihar Board class XII revised results uploaded.";

export const DEFAULT_SETTINGS: SiteSettings = {
  siteName: "Sarkari Result Live",
  tagline: "India's No.1 Premium Interactive Government Job Notification Gateway",
  email: "support@sarkariresultlive.in",
  pubId: "ca-pub-9988220011554477",
  headerSlot: "8899775533",
  sidebarSlot: "1122334455"
};
